### ISSUE TITLE
Add example files and screenshots

### ISSUE THREAD

**Issue by adina** [germs-lab/wafergen#1]
Few suggestions:
I find it incredibly useful to have the example files (even just the first few lines) in the repo and easily accessible.  It'd be great to have a screen shot of what the user should have in these files in the tutorial also.

Also, Can you put a brief intro into what this program is.  e.g., In order to submit your plate to MSU services for Wafergen, you must provide....because....

**Comment by adina** [comment]
@metajinomics

**Comment by metajinomics** [comment]
Thank you very much for your suggestion. For Python code, the example files are already in the repo. I created this python code and R code for very specific use case in the lab. I also trained each users who requested me to write this code. All current users should know who to use it. However, it is great suggestion about more detailed documentation. Thank you for your great suggestion and let me working on it.

For R code, I am still working on it. Please give me some time.

**Comment by metajinomics** [comment]
@adina I guess this issue was taken care of. Please check this. http://germslab.org/wafergen/wafergenR.html
